//生成配置 Spawning Configuration

var configSpawn = [
    { W51S59:
        [
            {
                listnum:1,
                set:"L1_Harvester01",
                body:[{work:1},{carry:1},{move:1}],
                number:0,
                role:"harvester",
                dest:{target:0},
                comment:"前往资源点一的一级开采虫"
            },
            {
                listnum:2,
                set:"L1_Harvester02",
                body:[{work:1},{carry:1},{move:1}],
                number:0,
                role:"harvester",
                dest:{target:1},
                comment:"前往资源点二的一级开采虫"
            },
            {
                listnum:3,
                set:"L2_Harvester01",
                body:[{work:1},{carry:3},{move:1}],
                number:0,
                role:"harvester",
                dest:{target:0},
                comment:"前往资源点一的二级开采虫"
            },
            {
                listnum:4,
                set:"L2_Harvester02",
                body:[{work:1},{carry:3},{move:1}],
                number:0,
                role:"harvester",
                dest:{target:0},
                comment:"前往资源点二的二级开采虫"
            },
            {
                listnum:5,
                set:"L3_Harvester01",
                body:[{work:1},{carry:3},{move:1}],
                number:10,
                role:"harvester",
                dest:{target:0},
                comment:"前往资源点二的三级开采虫"
            },
            {
                listnum:6,
                set:"L3_Harvester02",
                body:[{work:1},{carry:3},{move:1}],
                number:0,
                role:"harvester",
                dest:{target:0},
                comment:"前往资源点二的三级开采虫"
            },
            {
                listnum:7,
                set:"L1_Upgrader01",
                body:[{work:1},{carry:2},{move:1}],
                number:0,
                role:"upgrader",
                dest:{target:null},
                comment:"三心二意升级RCL的一级升级虫"
            },
            {
                listnum:8,
                set:"L2_Upgrader01",
                body:[{work:2},{carry:3},{move:1}],
                number:3,
                role:"harvester",
                dest:{target:null},
                comment:"略微专心升级RCL的二级升级虫"
            },
            {
                listnum:9,
                set:"L1_Builder01",
                body:[{work:1},{carry:1},{move:1}],
                number:5,
                role:"builder",
                dest:{target:null},
                comment:"不知道如何建造的建造虫"
            },
            {
                listnum:10,
                set:"L2_Builder02",
                body:[{work:2},{carry:2},{move:1}],
                number:0,
                role:"builder",
                dest:{target:null},
                comment:"初中学历就毕业的建造虫"
            }
        ]
    },
    { W59N32:
        [
            1,2
        ]
    }
];

module.exports = configSpawn;
